WITH RECURSIVE PROJECT_HIERARCHY AS (
  SELECT 
    P.SITE_ID AS SITE_ID, 
    P.ID, 
    P.NAME, 
    P.PARENT_PROJECT_ID, 
    P.CONTROLLING_PERMISSIONS_PROJECT_ID, 
    P2.NAME AS CONTROL_PROJECT_NAME, 
    P3.NAME AS PARENT_PROJECT_NAME, 
    1 AS LVL 
  FROM 
    PROJECTS P 
    LEFT JOIN PROJECTS P2 ON P.CONTROLLING_PERMISSIONS_PROJECT_ID = P2.ID 
    LEFT JOIN PROJECTS P3 ON P.PARENT_PROJECT_ID = P3.ID 
	
  UNION ALL 
	
  SELECT 
    PH.SITE_ID, 
    P2.ID, 
    P2.NAME, 
    P2.PARENT_PROJECT_ID, 
    P2.CONTROLLING_PERMISSIONS_PROJECT_ID, 
    P4.NAME AS CONTROL_PROJECT_NAME, 
    P5.NAME AS PARENT_PROJECT_NAME, 
    PH.LVL + 1 AS LVL 
  FROM 
    PROJECT_HIERARCHY PH 
    JOIN PROJECTS P2 ON PH.PARENT_PROJECT_ID = P2.ID 
    LEFT JOIN PROJECTS P4 ON P2.CONTROLLING_PERMISSIONS_PROJECT_ID = P4.ID 
    LEFT JOIN PROJECTS P5 ON P2.PARENT_PROJECT_ID = P5.ID 
  WHERE 
    PH.LVL < 6
), 

BASE_PROJECT_HIERARCHY AS (
  SELECT 
    PH.SITE_ID, 
    PH.ID, 
    PH.NAME, 
    PH.CONTROLLING_PERMISSIONS_PROJECT_ID, 
    PH.CONTROL_PROJECT_NAME, 
    PH.PARENT_PROJECT_NAME, 
    CONCAT_WS(
      '\',

        PH.CONTROL_PROJECT_NAME,
        PH6.NAME,
        PH5.NAME,
        PH4.NAME,
        PH3.NAME,
        PH2.NAME,
        PH.NAME) AS "path"
    FROM PROJECT_HIERARCHY PH
    LEFT JOIN PROJECT_HIERARCHY PH2 ON PH.PARENT_PROJECT_ID = PH2.ID
    AND PH2.LVL = 2
    LEFT JOIN PROJECT_HIERARCHY PH3 ON PH2.PARENT_PROJECT_ID = PH3.ID
    AND PH3.LVL = 3
    LEFT JOIN PROJECT_HIERARCHY PH4 ON PH3.PARENT_PROJECT_ID = PH4.ID
    AND PH4.LVL = 4
    LEFT JOIN PROJECT_HIERARCHY PH5 ON PH4.PARENT_PROJECT_ID = PH5.ID
    AND PH5.LVL = 5
    LEFT JOIN PROJECT_HIERARCHY PH6 ON PH5.PARENT_PROJECT_ID = PH6.ID
    AND PH6.LVL = 6
    WHERE PH.LVL = 1 ),
  FINAL_PROJECT_HIERARCHY AS
  (SELECT SITE_ID,
      ID AS PROJECT_ID,
      NAME AS PROJECT_NAME,
      CONTROL_PROJECT_NAME,
      PARENT_PROJECT_NAME,
      PATH
    FROM BASE_PROJECT_HIERARCHY
    GROUP BY SITE_ID,
      ID,
      NAME,
      CONTROL_PROJECT_NAME,
      PARENT_PROJECT_NAME,
      PATH),

LATEST_USER_ROLES AS (SELECT * FROM 
    (
      SELECT 
        HU.USER_ID, 
        HU.SYSTEM_USER_ID, 
        HU.NAME AS USER_NAME, 
        HU.SITE_ROLE_ID AS USER_TYPE_CODE, 
        SR.NAME AS USER_TYPE, 
        SR.DISPLAY_NAME, 
        MAX(HE.CREATED_AT) AS LATEST_USE_DATE, 
        ROW_NUMBER() OVER (
          PARTITION BY HU.SYSTEM_USER_ID 
          ORDER BY 
            MAX(HE.CREATED_AT) DESC
        ) AS RN 
      FROM 
        HISTORICAL_EVENTS HE 
        LEFT JOIN HIST_USERS HU ON HE.HIST_ACTOR_USER_ID = HU.ID 
        LEFT JOIN SITE_ROLES SR ON HU.SITE_ROLE_ID = SR.ID 
      GROUP BY 
        HU.USER_ID, 
        HU.SYSTEM_USER_ID, 
        HU.NAME, 
        HU.SITE_ROLE_ID, 
        SR.NAME, 
        SR.DISPLAY_NAME
    ) AS SUBQUERY 
  WHERE 
    RN = 1
), 

EVENT_SUMMARY AS (
  SELECT 
    -------------------------------
    -- Event Details summary
    HE.HISTORICAL_EVENT_TYPE_ID, 
    HET.NAME AS EVENT_TYPE, 
    HET.ACTION_TYPE, 
    -------------------------------
    -- Day time this is used
    HE.CREATED_AT, 
    -------------------------------
	--Sites Details
	CASE 
	WHEN HIST_TARGET_SITE_ID=3 THEN 'Sykes'
	WHEN HIST_TARGET_SITE_ID=2 THEN 'Bachcare'
	ELSE 'No Sites' END AS SITES,
	
	-------------------------------
    --user who initiated action
    HE.HIST_ACTOR_USER_ID, 
    HU.SYSTEM_USER_ID AS USER_ID, 
    HU.NAME AS USER_NAME, 
    HU.SITE_ROLE_ID AS USER_TYPE_CODE, 
    LUR.DISPLAY_NAME AS USER_TYPE, 
    COALESCE(SU.STATE, 'DEACTIVATED') AS USER_STATUS, 
    HE.HIST_TARGET_SITE_ID, 
    -------------------------------
    --Project Details
    HE.HIST_PROJECT_ID, 
    HP.PROJECT_ID, 
    HP.NAME AS PROJECT_NAME, 
    COALESCE(PH.CONTROL_PROJECT_NAME,'@'||HP.NAME) AS CONTROL_PROJECT_NAME , 
    COALESCE(PH.PARENT_PROJECT_NAME,'@'||HP.NAME) AS  PARENT_PROJECT_NAME,
	PH.PATH,
    -------------------------------
    -------------------------------
    --PROJECT_HIERARCHY details
--     PH.PROJECT_ID AS PROJECT_ID_H, 
--     PH.PROJECT_NAME AS PROJECT_NAME_H, 
--     PH.CONTROL_PROJECT_ID, 
--     PH.CONTROL_PROJECT_NAME, 
--     PH.PARENT_PROJECT_ID, 
--     PH.PARENT_PROJECT, 
    -------------------------------
    --Workbook details
    HE.HIST_WORKBOOK_ID, 
    HW.WORKBOOK_ID, 
    _W.NAME AS WORKBOOK_NAME, 
    --------------------------------
    --View details
    HE.HIST_VIEW_ID, 
    HV.VIEW_ID, 
    HV.NAME AS VIEW_NAME, 
    --------------------------------
    --Connected datasource
    HE.HIST_DATASOURCE_ID, 
    HD.DATASOURCE_ID, 
    HD.NAME AS DATASOURCE_NAME 
	---------------------------------
    --userful for the future
    -- he.hist_group_id,
    -- he.hist_licensing_role_id,
    -- he.hist_data_connection_id,
    -- he.hist_capability_id
    ---------------------------------
  FROM 
    HISTORICAL_EVENTS HE 
    LEFT JOIN HISTORICAL_EVENT_TYPES HET ON HE.HISTORICAL_EVENT_TYPE_ID = HET.TYPE_ID 
    LEFT JOIN HIST_USERS HU ON HE.HIST_ACTOR_USER_ID = HU.ID 
    LEFT JOIN HIST_PROJECTS HP ON HE.HIST_PROJECT_ID = HP.ID 
    LEFT JOIN HIST_WORKBOOKS HW ON HE.HIST_WORKBOOK_ID = HW.ID 
	LEFT JOIN _WORKBOOKS _W ON HW.WORKBOOK_ID=_W.ID
    LEFT JOIN HIST_VIEWS HV ON HE.HIST_VIEW_ID = HV.ID 
    LEFT JOIN HIST_DATASOURCES HD ON HE.HIST_DATASOURCE_ID = HD.ID 
    LEFT JOIN FINAL_PROJECT_HIERARCHY PH ON HP.PROJECT_ID = PH.PROJECT_ID 
    LEFT JOIN LATEST_USER_ROLES LUR ON HU.SYSTEM_USER_ID = LUR.SYSTEM_USER_ID 
    LEFT JOIN SYSTEM_USERS SU ON HU.SYSTEM_USER_ID = SU.ID
    INNER JOIN _WORKBOOKS W ON HW.WORKBOOK_ID=W.ID
) 
SELECT 
  * 
FROM 
  EVENT_SUMMARY 
WHERE 
  CREATED_AT >= CURRENT_DATE - interval '91 days' 
  AND HISTORICAL_EVENT_TYPE_ID = 84
  and workbook_name like 
'6%'

-- SELECT * FROM WORKBOOKS WHERE NAME LIKE '6%'
